### ISSUE TITLE
Ajustar diagramas de Caso de Uso Orçamento e Funcionarios.

### ISSUE THREAD

**Issue by rafaelnator** [vidacalura/BonziTech-TCC#1]

**Comment by vidacalura** [comment]
Caro rafaelnator, as issues são reservadas a problemas ou adições ao código, não se referindo à documentação, que deve ser tratada em privado com os colaboradores do time. Peço que você faça suas alterações dos diagramas e documentação no GitHub projects ou então, por meio do discord.

Agradeço a compreensão
